apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: workloads-ai:argoproj.io/Application:argo-cd/sd-comfyui
    argocd.argoproj.io/sync-wave: '30'
  labels:
    app.kubernetes.io/instance: sd-comfyui
    app.kubernetes.io/component: sd-comfyui
    app.kubernetes.io/part-of: workloads-ai
  name: sd-comfyui-chart
  namespace: argo-cd
spec:
  destination:
    namespace: sd-comfyui
    server: https://kubernetes.default.svc
  project: workloads-ai
  sources:
    - helm:
        valueFiles:
          - >-
            $values/src/workloads/ai/sd-comfyui/values.yaml
      path: helm/sd-comfyui
      repoURL: https://github.com/Kube-Mind/stable-diffusion-webui.git
      targetRevision: main
    - ref: values
      repoURL: https://github.com/Kube-Mind/fleet-infra.git
      targetRevision: main
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
      - '.spec.volumeClaimTemplates[]'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true