apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads-work
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: workloads:argoproj.io/Application:argo-cd/work
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: work
    app.kubernetes.io/part-of: workloads
    app.kubernetes.io/managed-by: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - name: pft
          wave: 50
        - name: ska
          wave: 50
  template:
    metadata:
      name: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: workloads-work:argoproj.io/Application:argo-cd/{{ .name }}
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/instance: '{{ .name }}'
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: workloads-work
    spec:
      project: workloads-work
      source:
        repoURL: https://github.com/Kube-Mind/fleet-infra.git
        targetRevision: main
        path: 'src/workloads/work/{{ .name }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ .name }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true