apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- external-secret.yaml

helmCharts:
- name: external-dns
  namespace: external-dns
  releaseName: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns/
  valuesFile: values.yaml
  version: 1.20.0
