apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik
  namespace: traefik
  releaseName: traefik
  repo: https://traefik.github.io/charts
  valuesFile: traefik.values.yaml
  version: 38.0.1
- name: traefik-crds
  namespace: traefik
  releaseName: traefik
  repo: https://traefik.github.io/charts
  valuesFile: traefik-crds.values.yaml
  version: 1.12.0

resources:
- namespace.yaml