apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik
  namespace: traefik
  releaseName: traefik
  repo: https://traefik.github.io/charts
  valuesFile: traefik.values.yaml
  version: 37.4.0
- name: traefik-crds
  namespace: traefik
  releaseName: traefik
  repo: https://traefik.github.io/charts
  valuesFile: traefik-crds.values.yaml
  version: 1.13.0

resources:
- namespace.yaml