apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-network
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: platform:argoproj.io/Application:argo-cd/network
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: platform-network
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argo-cd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: dnsfix
            wave: 30
          - name: cilium
            wave: -20
            ignoreDifferences:
              - group: ''
                kind: Secret
                name: cilium-ca
                jsonPointers:
                  - /data/ca.crt
                  - /data/ca.key
              - group: ''
                kind: Secret
                name: hubble-server-certs
                jsonPointers:
                  - /data/ca.crt
                  - /data/tls.crt
                  - /data/tls.key
          - name: letsencrypt
            wave: 10
          - name: metallb
            wave: -10
          - name: traefik
            wave: 10
  template:
    metadata:
      name: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: platform-network:argoproj.io/Application:argo-cd/{{ .name }}
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/instance: '{{ .name }}'
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: platform-network
    spec:
      project: platform-network
      source:
        repoURL: https://github.com/Kube-Mind/fleet-infra.git
        targetRevision: main
        path: 'src/platform/network/{{ .name }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ .name }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
  templatePatch: |
    {{- if .ignoreDifferences }}
    spec:
      ignoreDifferences:
      {{- toYaml .ignoreDifferences | nindent 12 }}
    {{- end }}