apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-workflows
  namespace: argo-workflows
  repo: https://argoproj.github.io/argo-helm
  valuesFile: workflows.values.yaml
  version: 0.47.3
  includeCRDs: true

- name: argo-events
  namespace: argo-workflows
  repo: https://argoproj.github.io/argo-helm
  valuesFile: events.values.yaml
  version: 2.4.20
  includeCRDs: true