apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- external-secret.yaml

helmCharts:
- name: jupyterhub
  namespace: jupyterhub
  repo: https://jupyterhub.github.io/helm-chart
  valuesFile: values.yaml
  version: 4.3.2
  includeCRDs: true