apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-external-secret
  namespace: kube-prometheus-stack
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/observability/grafana
        metadataPolicy: None
        property: GITLAB_APPLICATION_ID
      secretKey: GF_AUTH_GITLAB_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/observability/grafana
        metadataPolicy: None
        property: GITLAB_CLIENT_SECRET
      secretKey: GF_AUTH_GITLAB_CLIENT_SECRET
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: GRAFANA_CLIENT_ID
      secretKey: GF_AUTH_AUTHENTIK_CLIENT_ID
      # GF_AUTH_GENERIC_OAUTH_CLIENT_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: platform/security/authentik
        metadataPolicy: None
        property: GRAFANA_CLIENT_SECRET
      secretKey: GF_AUTH_AUTHENTIK_CLIENT_SECRET
      # GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: grafana-external-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd