apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml

helmCharts:
- name: promtail
  namespace: promtail
  releaseName: promtail
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 6.17.1
  includeCRDs: true