apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: workloads-work:argoproj.io/Application:argo-cd/ska-pst-test-parent
    argocd.argoproj.io/sync-wave: '30'
  labels:
    app.kubernetes.io/instance: ska-pst-test-parent
    app.kubernetes.io/component: ska-pst-test-parent
    app.kubernetes.io/part-of: workloads-work
  name: ska-pst-test-parent
  namespace: argo-cd
spec:
  destination:
    namespace: ska
    server: https://kubernetes.default.svc
  project: workloads-work
  sources:
    - helm:
        releaseName: test
        valueFiles:
          - >-
            $values/src/workloads/work/ska/test-parent/values.yaml
      path: charts/test-parent
      repoURL: https://gitlab.com/ska-telescope/pst/ska-pst.git
      targetRevision: main
    - ref: values
      repoURL: https://github.com/Kube-Mind/fleet-infra.git
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true