apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- external-secret.yaml
- configmap.yaml
- immich-database
- immich-redis
- immich-machine-learning
- immich-server
- ingress.yaml
- middleware.yaml