apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka-applications
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: kafka:argoproj.io/Application:argo-cd/kafka-applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: kafka-applications
    app.kubernetes.io/part-of: kafka
    app.kubernetes.io/managed-by: argo-cd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: kafka-cluster
            wave: 40
          - name: kafka-operator
            wave: 30
  template:
    metadata:
      name: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: kafka-applications:argoproj.io/Application:argo-cd/{{ .name }}
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/instance: '{{ .name }}'
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: kafka-applications
    spec:
      project: workloads-messaging
      source:
        repoURL: https://github.com/Kube-Mind/fleet-infra.git
        targetRevision: main
        path: 'src/workloads/messaging/kafka/{{ .name }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: kafka
        server: https://kubernetes.default.svc
      syncPolicy:
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
  templatePatch: |
    {{- if .ignoreDifferences }}
    spec:
      ignoreDifferences:
      {{- toYaml .ignoreDifferences | nindent 12 }}
    {{- end }}