apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- external-secret.yaml

helmCharts:
- name: argo-cd
  namespace: argo-cd
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
  version: 9.4.6