apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cilium
  namespace: cilium
  releaseName: cilium
  repo: https://helm.cilium.io/
  valuesFile: values.yaml
  version: 1.19.1

resources:
- namespace.yaml
- announcement-policy.yaml
- ip-pool.yaml