k8sServiceHost: 172.16.1.14
k8sServicePort: 6443
kubeProxyReplacement: true

gatewayAPI:
  enabled: true

# Network Policy Audit Mode - Log violations without blocking
# policyAuditMode: true

# ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
# tolerations:
#   - key: node-role.kubernetes.io/control-plane
#     operator: Exists
#     effect: NoSchedule
#   - key: node-role.kubernetes.io/etcd
#     operator: Exists
#     effect: NoExecute

# envoy:
#   tolerations:
#     - key: node-role.kubernetes.io/control-plane
#       operator: Exists
#       effect: NoSchedule
#     - key: node-role.kubernetes.io/etcd
#       operator: Exists
#       effect: NoExecute

hubble:
  relay:
    enabled: false
  ui:
    enabled: false
  
      # - dns
      # - drop
      # - tcp
      # - flow
      # - icmp
      # - http # This enables L7 visibility for HTTP
