k8sServiceHost: 10.1.1.14
k8sServicePort: 6443
kubeProxyReplacement: true

devices: "enp+"
# ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
# tolerations:
#   - key: node-role.kubernetes.io/etcd
#     operator: Exists
#     effect: NoExecute
# 
# envoy:
#   tolerations:
#     - key: node-role.kubernetes.io/etcd
#       operator: Exists
#       effect: NoExecute

hubble:
  relay:
    enabled: false
  ui:
    enabled: false
  metrics:
    enabled: ~
      # - dns
      # - drop
      # - tcp
      # - flow
      # - icmp
      # - http # This enables L7 visibility for HTTP
