k8sServiceHost: 172.16.1.14
k8sServicePort: 6443
kubeProxyReplacement: true

ipam:
  operator:
    # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

# ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
tolerations:
  - key: node-role.kubernetes.io/etcd
    operator: Exists
    effect: NoSchedule
# 
# envoy:
#   tolerations:
#     - key: node-role.kubernetes.io/etcd
#       operator: Exists
#       effect: NoExecute

hubble:
  relay:
    enabled: false
  ui:
    enabled: false
  
      # - dns
      # - drop
      # - tcp
      # - flow
      # - icmp
      # - http # This enables L7 visibility for HTTP
