apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: gitlab-runner
  namespace: gitlab-runner
  repo: https://charts.gitlab.io
  valuesFile: values.yaml
  version: 0.83.3
  includeCRDs: true