apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-core
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/tracking-id: platform:argoproj.io/Application:argo-cd/core
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: core
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argo-cd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
        - name: argo-cd
          wave: 0
        - name: cert-manager
          wave: 10
        - name: external-secrets
          wave: 10
        - name: nvidia-operator
          wave: 10
          ignoreDifferences:
            - group: nvidia.com
              kind: ClusterPolicy
              name: cluster-policy
              jsonPointers:
                - /spec/migManager/config/name
        - name: system-upgrade
          wave: 10
        - name: system-upgrade-plans
          wave: 20
  template:
    metadata:
      name: '{{ .name }}'
      annotations:
        argocd.argoproj.io/tracking-id: platform-core:argoproj.io/Application:argo-cd/{{ .name }}
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      labels:
        app.kubernetes.io/instance: '{{ .name }}'
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: platform-core
    spec:
      project: platform-core
      source:
        repoURL: https://github.com/Kube-Mind/fleet-infra.git
        targetRevision: main
        path: 'src/platform/core/{{ .name }}'
        kustomize: {} # Let Kustomize handle naming
      destination:
        namespace: '{{ .name }}'
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
  templatePatch: |
    {{- if .ignoreDifferences }}
    spec:
      ignoreDifferences:
      {{- toYaml .ignoreDifferences | nindent 12 }}
    {{- end }}