apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.46.0/strimzi-crds-0.46.0.yaml # CRDs must be applied first

helmCharts:
- name: strimzi-kafka-operator
  namespace: kafka
  releaseName: kafka
  repo: https://strimzi.io/charts/
  valuesFile: values.yaml
  version: 0.49.0
